### PR TITLE
JavaScript Best Practices

### PR DESCRIPTION
**Pull request by aboongm**
Check the quality of the code. Remember to check for the following:
- JavaScript Best Practices
- DRY, KISS, and YAGNI
- HTML, and CSS Best Practices

### CODE REVIEW

**Comment by Estherstarr** [comment]
Hi Aboogm, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Good Points 👍  
- Descriptive Pull Request
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Estherstarr** [comment]
- [ ] OPTIONAL
  - Kindly clear input bar after entering task.
Screenshot 2022-04-04 at 12 33 37 PM

**Comment by Estherstarr** [comment]
- FOR THE REFRESH BUTTON
  - When the first item is deleted,  the second task description is emptied from the local storage
  - Also when the page is refreshed, the second item is not seen in the user interface
  - [ ] You need to implement a function to store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

**Comment by Estherstarr** [comment]
CHECKBOX
- When I click on the checkbox, the description('') text is removed from the local storage. 
The only changes required in the local storage,  change the completed value from 'true' to 'false' vice versa

**Comment by aboongm** [comment]
> * box, the description('') text is

its is now fixed.

**Comment by aboongm** [comment]
> * FOR THE REFRESH BUTTON
>       
>       * When the first item is deleted,  the second task description is emptied from the local storage
>       * Also when the page is refreshed, the second item is not seen in the user interface
>       * [ ]  You need to implement a function to store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

these are now fixed.

**Comment by aboongm** [comment]
> * [ ]  OPTIONAL
>       
>       * Kindly clear input bar after entering task.
> 
> 
> Screenshot 2022-04-04 at 12 33 37 PM

This could be achieved by removing the event.preventDefault(); in the event listener handling the press enter. But I like to keep these words in the input field.

**Comment by Estherstarr** [comment]
# Hi @aboongm  👋, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
